version: "2"
run:
  build-tags:
    - integration
  modules-download-mode: readonly

output:
  formats:
    tab:
      path: stdout
      colors: false

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errname
    - godot
    - misspell
    - noctx
    - revive
    - unconvert
    - unparam
    - usetesting
  settings:
    errcheck:
      exclude-functions:
        - (*go.uber.org/zap.Logger).Sync
  exclusions:
    generated: lax
    paths:
      - "3rdparty/"
    rules:
    # Simplified does not necessarily mean more readable
    - linters: ["staticcheck"]
      text: "QF1001: could apply De Morgan's law"
    # This case triggers too many false positives from error strings that start with product names
    # e.g. MarbleRun or Coordinator
    - linters: ["staticcheck"]
      text: "ST1005: error strings should not be capitalized"
    # Disabled since we don't use package comments in large parts of our internal codebase
    - linters: ["revive"]
      text: "package-comments: package comment should be of the form"
    - linters: ["revive"]
      text: "package-comments: should have a package comment"
    presets:
      # Disabled since this rule enforces error checks on fmt.FprintX and Close methods
      - std-error-handling

formatters:
  enable:
    - gofmt
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 20
