// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.0
// source: keyserver.proto

package keypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKeyEncryptionKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// quote is an SGX quote over the TLS certificate of the requesting enclave.
	Quote []byte `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
}

func (x *GetKeyEncryptionKeyRequest) Reset() {
	*x = GetKeyEncryptionKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keyserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeyEncryptionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyEncryptionKeyRequest) ProtoMessage() {}

func (x *GetKeyEncryptionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyEncryptionKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyEncryptionKeyRequest) Descriptor() ([]byte, []int) {
	return file_keyserver_proto_rawDescGZIP(), []int{0}
}

func (x *GetKeyEncryptionKeyRequest) GetQuote() []byte {
	if x != nil {
		return x.Quote
	}
	return nil
}

type GetKeyEncryptionKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key is the key encryption key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetKeyEncryptionKeyResponse) Reset() {
	*x = GetKeyEncryptionKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keyserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeyEncryptionKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyEncryptionKeyResponse) ProtoMessage() {}

func (x *GetKeyEncryptionKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyEncryptionKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyEncryptionKeyResponse) Descriptor() ([]byte, []int) {
	return file_keyserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetKeyEncryptionKeyResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_keyserver_proto protoreflect.FileDescriptor

var file_keyserver_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6b, 0x65, 0x79, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x22, 0x32, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4b,
	0x65, 0x79, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x22, 0x2f, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32, 0x63, 0x0a,
	0x03, 0x41, 0x50, 0x49, 0x12, 0x5c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x21, 0x2e, 0x6b, 0x65,
	0x79, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x54, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x64, 0x67, 0x65, 0x6c, 0x65, 0x73, 0x73, 0x73, 0x79, 0x73, 0x2f, 0x6d, 0x61, 0x72,
	0x62, 0x6c, 0x65, 0x72, 0x75, 0x6e, 0x2d, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73,
	0x65, 0x2f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2f, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x72, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keyserver_proto_rawDescOnce sync.Once
	file_keyserver_proto_rawDescData = file_keyserver_proto_rawDesc
)

func file_keyserver_proto_rawDescGZIP() []byte {
	file_keyserver_proto_rawDescOnce.Do(func() {
		file_keyserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_keyserver_proto_rawDescData)
	})
	return file_keyserver_proto_rawDescData
}

var file_keyserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_keyserver_proto_goTypes = []interface{}{
	(*GetKeyEncryptionKeyRequest)(nil),  // 0: keypb.GetKeyEncryptionKeyRequest
	(*GetKeyEncryptionKeyResponse)(nil), // 1: keypb.GetKeyEncryptionKeyResponse
}
var file_keyserver_proto_depIdxs = []int32{
	0, // 0: keypb.API.GetKeyEncryptionKey:input_type -> keypb.GetKeyEncryptionKeyRequest
	1, // 1: keypb.API.GetKeyEncryptionKey:output_type -> keypb.GetKeyEncryptionKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keyserver_proto_init() }
func file_keyserver_proto_init() {
	if File_keyserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keyserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeyEncryptionKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keyserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeyEncryptionKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keyserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keyserver_proto_goTypes,
		DependencyIndexes: file_keyserver_proto_depIdxs,
		MessageInfos:      file_keyserver_proto_msgTypes,
	}.Build()
	File_keyserver_proto = out.File
	file_keyserver_proto_rawDesc = nil
	file_keyserver_proto_goTypes = nil
	file_keyserver_proto_depIdxs = nil
}
