{{- if .Values.pullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.token }}
{{- end }}
