{{ if .Values.dcap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: coordinator-dcap-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: dcap-config
    app.kubernetes.io/created-by: {{ .Values.global.createdBy }}
    app.kubernetes.io/name: coordinator-dcap-config
    app.kubernetes.io/part-of: marblerun
    app.kubernetes.io/version: {{ .Values.coordinator.version }}
    {{ .Values.global.coordinatorComponentLabel }}: dcap-config
    {{ .Values.global.coordinatorNamespaceLabel }}: {{ .Release.Namespace }}
data:
  sgx_default_qcnl.conf: |
    PCCS_URL={{ .Values.dcap.pccsUrl }}
    USE_SECURE_CERT={{ .Values.dcap.useSecureCert }}
{{ end }}
