#!/bin/bash

exec env EDG_KUBERNETES_SERVICE_HOST="${KUBERNETES_SERVICE_HOST}" \
    env EDG_KUBERNETES_SERVICE_PORT="${KUBERNETES_SERVICE_PORT}" \
    env EDG_AZURE_CLIENT_ID="${AZURE_CLIENT_ID:-${EDG_AZURE_CLIENT_ID}}" \
    env EDG_AZURE_TENANT_ID="${AZURE_TENANT_ID:-${EDG_AZURE_TENANT_ID}}" \
    env EDG_AZURE_FEDERATED_TOKEN_FILE="${AZURE_FEDERATED_TOKEN_FILE}" \
    env EDG_AZURE_AUTHORITY_HOST="${AZURE_AUTHORITY_HOST}" \
    erthost coordinator-enclave.signed
