name: Create Pull Request for CLI reference update
on:
  workflow_dispatch:
  push:
    branches:
      - action/marblerun/update-cli-reference

jobs:
  pull-request:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ !github.event.pull_request.head.repo.fork && github.head_ref || '' }}

      - name: pull-request
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 # v2.12.1
        with:
          destination_branch: "master"
          pr_title: "docs: update cli reference"
          pr_body: |
            :robot: *This is an automated PR.* :robot:

            Changes in the CLI triggered this PR, it updates the corresponding documentation page.
          github_token: ${{ secrets.GITHUB_TOKEN }}
