name: 'Test: links'

on:
  push:
    branches:
      - master
    paths:
      - "**.md"
      - "**.html"
      - ".github/workflows/links.yml"
  pull_request:
    paths:
      - "**.md"
      - "**.html"
      - ".github/workflows/links.yml"
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Link Checker
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          fail: true
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst' --cache --cache-exclude-status 400..599 --max-concurrency 4 --retry-wait-time 60
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
