name: 'Test: lint'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/lint.yml"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-24.04
    container: ghcr.io/edgelesssys/edgelessrt-dev:ci
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          skip-cache: true
          args: --timeout=30m
