name: Publish OpenAPI specification to documentation
on:
  push:
    branches:
      - master

jobs:
  publish-to-docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:ci

    steps:
      # Install requirements
      - name: Install jq
        run: apt install -y jq

      - name: Create download URL
        run: echo "download_url=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/latest | jq -r '.assets[] | select(.name | contains("'"$(uname | tr '[:upper:]' '[:lower:]')"'_amd64")) | .browser_download_url')" >> $GITHUB_ENV

      - name: Download go-swagger
        run: curl -o /usr/local/bin/swagger -L'#' ${{ env.download_url }}

      - name: Make file executable
        run: chmod +x /usr/local/bin/swagger

      - name: Check Swagger version
        run: swagger version

      # Set up repositories
      - name: Checkout MarbleRun
        uses: actions/checkout@v3

      # Generate Swagger specification
      - name: Generate Swagger file from annotations
        run: swagger generate spec -m --compact --exclude-deps -o ./swagger.json
        env:
          SWAGGER_GENERATE_EXTENSION: false

      - name: Validate Swagger
        run: swagger validate ./swagger.json

      # If spec changed, commit new spec to the documentation
      - name: Get number of triggering PR or commit sha
        run: |
          sha_short=$(echo "${{ github.sha }}" | cut -c1-8)
          pr_number=$(curl -s -H 'Accept: application/vnd.github.groot-preview+json' https://api.github.com/repos/edgelesssys/marblerun/commits/${{ github.sha }}/pulls | jq -r '.[].number')
          ending=$(if [ -n "$pr_number" ]; then echo "#$pr_number"; else echo "@$sha_short"; fi)
          echo "COMMIT_END=$ending" >> $GITHUB_ENV

      - name: Check if action branch exists
        run: |
          ex=$(git ls-remote --heads origin action/update-swagger)
          echo "EXISTS=$(if [ -z "$ex" ]; then echo 0; else echo 1; fi)" >> $GITHUB_ENV

      - name: Publish new specification (create new branch)
        if: ${{ env.EXISTS == 0 }}
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.CI_GITHUB_REPOSITORY }}
        with:
          source_file: "swagger.json"
          destination_repo: "edgelesssys/marblerun"
          destination_branch_create: "action/update-swagger"
          destination_folder: "docs/openapi/coordinator/"
          user_name: "${{ github.actor }}"
          user_email: "${{ github.actor }}@users.noreply.github.com"
          commit_message: "OpenAPI spec was updated by edgelesssys/marblerun${{ env.COMMIT_END}}"

      - name: Publish new specification (update branch)
        if: ${{ env.EXISTS == 1 }}
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.CI_GITHUB_REPOSITORY }}
        with:
          source_file: "swagger.json"
          destination_repo: "edgelesssys/marblerun"
          destination_branch: "action/update-swagger"
          destination_folder: "docs/openapi/coordinator/"
          user_name: "${{ github.actor }}"
          user_email: "${{ github.actor }}@users.noreply.github.com"
          commit_message: "OpenAPI spec was updated by edgelesssys/marblerun${{ env.COMMIT_END}}"
