name: 'Check: require label'

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    steps:
      - uses: mheap/github-action-required-labels@8afbe8ae6ab7647d0c9f0cfa7c2f939650d22509 # v5.5.1
        with:
          mode: minimum
          count: 1
          labels: |
            breaking change
            bug fix
            changelog
            dependencies
            feature
            documentation
            no changelog
