name: 'Check: require label'

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    steps:
      - uses: mheap/github-action-required-labels@388fd6af37b34cdfe5a23b37060e763217e58b03 # 5.5.0
        with:
          mode: minimum
          count: 1
          labels: |
            breaking change
            bug fix
            changelog
            dependencies
            feature
            documentation
            no changelog
