name: Unit Tests

on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "**/go.mod"
  pull_request:
    paths:
      - "**.go"
      - "**/go.mod"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:ci

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: ertgo test -race -count=3 ./...

      - name: Setup
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          mkdir build

      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          make
        working-directory: build

      - name: Integration test
        run: ertgo test -tags integration -b ../build -s
        working-directory: test

      - name: Integration test (-noenclave)
        run: ertgo test -tags integration -b ../build -noenclave
        working-directory: test

      - name: Build artifact
        uses: actions/upload-artifact@v2
        with:
          name: marblerun
          path: |
            build/coordinator-enclave.signed
            build/coordinator-noenclave
            build/coordinator-era.json
            build/premain-libos
            build/marble-injector
            build/marblerun

      - name: Deploy coordinator:nightly
        if: github.ref == 'refs/heads/master' &&
          github.event_name == 'push'
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.CI_GITHUB_REPOSITORY }}" \
          -d '{"event_type": "docker-build",
              "client_payload":{"repository":"marblerun",
                                "sign":"nightly",
                                "imagename":"marblerun/coordinator-debug",
                                "tag":"nightly",
                                "file": "dockerfiles/Dockerfile.coordinator",
                                "target":"release"}}' \
          https://api.github.com/repos/edgelesssys/deployment/dispatches

      - name: Deploy marble-injector:nightly
        if: github.ref == 'refs/heads/master' &&
          github.event_name == 'push'
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.CI_GITHUB_REPOSITORY }}" \
          -d '{"event_type": "docker-build",
              "client_payload":{"repository":"marblerun",
                                "sign":"nightly",
                                "imagename":"marblerun/marble-injector",
                                "tag":"nightly",
                                "file": "dockerfiles/Dockerfile.marble-injector",
                                "target":"release"}}' \
          https://api.github.com/repos/edgelesssys/deployment/dispatches
