name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:ci

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: coordinator

    - name: Test
      run: ertgo test -race ./...
      working-directory: coordinator

    - run: |
        mkdir coordinator/build assets
        SHA=$(echo ${{ github.sha }} | cut -c1-8)
        echo "GITSHA=$SHA" >> $GITHUB_ENV

    - name: Build
      run: |
        cmake .. && make
        cp coordinator-enclave.signed coordinator-noenclave coordinator-config.json public.pem private.pem ../../assets/
      working-directory: coordinator/build

    - name: Integration test
      run: ertgo test -tags integration -b ../build -s
      working-directory: coordinator/test
