name: Unit Tests

on:
  push:
    branches: [ feat/buildartifact ]
  pull_request:
    branches: [ feat/buildartifact ]

jobs:
  run:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/edgelesssys/edgelessrt-private:latest
      credentials:
        username: ${{ secrets.CI_GITHUB_PACKAGES_READ }}
        password: ${{ secrets.CI_GITHUB_PACKAGES_READ }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: coordinator
        ref: master

    - name: Test core
      run: ertgo test 
      working-directory: coordinator/coordinator/core

    - name: Test server
      run: ertgo test 
      working-directory: coordinator/coordinator/server

    - name: Test marble
      run: ertgo test 
      working-directory: coordinator/marble/marble

    - run: mkdir coordinator/build assets

    - name: Builder
      run: |
        cmake .. && make
        mv enclave.signed coordinator-noenclave config.json public.pem private.pem ../../assets/
      working-directory: coordinator/build
      
    - uses: actions/upload-artifact@v2
      with:
        name: wip(${{ github.sha }})
        path: assets
  