name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/edgelessrt-private:latest
      credentials:
        username: ${{ secrets.CI_GITHUB_PACKAGES_READ }}
        password: ${{ secrets.CI_GITHUB_PACKAGES_READ }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: coordinator

    - name: Test
      run: ertgo test ./...
      working-directory: coordinator

    - run: |
        mkdir coordinator/build assets
        SHA=$(echo ${{ github.sha }} | cut -c1-8)
        echo ::set-env name=GITSHA::$SHA

    - name: Build
      run: |
        cmake .. && make
        mv coordinator-enclave.signed coordinator-noenclave coordinator-config.json public.pem private.pem ../../assets/
      working-directory: coordinator/build

    - name: Delete old release assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: wip@${{ github.ref }}
        fail-if-no-assets: false
        fail-if-no-release: false
        assets: '*'

    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: wip(${{ env.GITSHA }})@${{ github.ref }}
        tag: wip@${{ github.ref }}
        gzip: false
        allow_override: true
        files: assets/*
