name: Unit Tests

on:
  push:
    branches: [ feat/nightlybuild ]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:ci

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: coordinator

    - name: Test
      run: ertgo test -race ./...
      working-directory: coordinator

    - run: |
        mkdir coordinator/build assets
        SHA=$(echo ${{ github.sha }} | cut -c1-8)
        echo "GITSHA=$SHA" >> $GITHUB_ENV

    - name: Build
      run: |
        cmake .. && make
        cp coordinator-enclave.signed coordinator-noenclave coordinator-config.json public.pem private.pem ../../assets/
      working-directory: coordinator/build

    - name: Integration test
      run: ertgo test -tags integration -b ../build -s
      working-directory: coordinator/test

    - name: query deployment repo for nightly build
      run: |
        curl -X POST -H "Accept:application/vnd.github.v3+json" \
        -H "Authorization:token ${{ secrets.CI_GITHUB_REPOSITORY }}" \
        -d '{"event_type":"nightly-build", "client_payload":{"repository":"marblerun", "imagename":"marblerun","target":"release"}}' \
        https://api.github.com/repos/edgelesssys/deployment/dispatches
