name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:ci

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: ertgo test -race ./...

    - name: Setup
      run: mkdir build

    - name: Build
      run: |
        cmake ..
        make
      working-directory: build

    - name: Integration test
      run: ertgo test -tags integration -b ../build -s
      working-directory: test
    
    - name: Integration test (-noenclave)
      run: ertgo test -tags integration -b ../build -noenclave
      working-directory: test

    - name: Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: marblerun
        path: |
          build/coordinator-enclave.signed
          build/coordinator-noenclave
          build/coordinator-era.json

    - name: Deploy coordinator:nightly
      if: github.ref == 'refs/heads/master' &&
          github.event_name == 'push'
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $CI_GITHUB_REPOSITORY" \
        -d '{"event_type": "docker-build",
            "client_payload":{"repository":"marblerun",
                              "sign":"nightly",
                              "imagename":"coordinator",
                              "tag":"nightly",
                              "target":"release"}}' \
        https://api.github.com/repos/edgelesssys/deployment/dispatches
