name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:ci

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: marblerun

    - name: Test
      run: ertgo test -race ./...
      working-directory: marblerun

    - name: Setup
      run: |
        mkdir marblerun/build assets
        SHA=$(echo ${{ github.sha }} | cut -c1-8)
        echo "GITSHA=$SHA" >> $GITHUB_ENV

    - name: Build
      run: |
        cmake .. && make
      working-directory: marblerun/build

    - name: Integration test
      run: ertgo test -tags integration -b ../build -s
      working-directory: marblerun/test

    - name: Build artifact
      uses: actions/upload-artifact@v2
      if: github.ref != 'refs/heads/master'
      with:
        name: marblerun
        path: |
          marblerun/build/coordinator-enclave.signed
          marblerun/build/coordinator-noenclave
          marblerun/build/coordinator-config.json
          marblerun/build/marble-test-enclave.signed
          marblerun/build/marble-test-noenclave
          marblerun/build/marble-test-config.json
          marblerun/build/public.pem

    - name: Deploy marblerun
      if: github.ref == 'refs/heads/master' &&
          github.event_name == 'push'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.CI_GITHUB_REPOSITORY }}
        repository: edgelesssys/deployment
        event-type: docker-build
        client-payload: '{"repository": "marblerun",
                          "type": "sign",
                          "imagename": "marblerun",
                          "tag": "nightly",
                          "target": "release"}'
