name: 'Test: vale spelling'
on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
  pull_request:
    paths:
      - "docs/**"

jobs:
  vale:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Vale
        uses: errata-ai/vale-action@85f9f7f2c5f449ac0ae5b66662961bae3f77ca6a # reviewdog
        with:
          files: docs/docs
          fail_on_error: true
          version: 3.9.3
