apiVersion: apps/v1
kind: Deployment
metadata:
  name: marble-injector
  namespace: marblerun
  labels:
    app: marble-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marble-injector
  template:
    metadata:
      labels:
        app: marble-injector
    spec:
      containers:
      - args:
        - -coordAddr=coordinator-mesh-api.marblerun:25554 # this needs to be conditionaly set through helm chart
        - -tlsCertFile=/etc/webhook/certs/cert.pem
        - -tlsKeyFile=/etc/webhook/certs/key.pem
        name: marble-injector
        image: test/marblewebhook:v1 # image should be set to webhook:latest 
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
        ports:
          - containerPort: 8443
            name: http

      volumes:
      - name: webhook-certs
        secret:
          secretName: marble-injector-webhook-certs