apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: marble-injector
  labels:
    app: marble-injector
webhooks:
  - name: marble-injector.cluster.local
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        name: marble-injector
        namespace: marblerun
        path: "/mutate"
    rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: "Namespaced"
    namespaceSelector:
      matchLabels:
        marblerun/monitor: marblerun
        marblerun/injectsgx: enabled
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
  - name: marble-injector-no-sgx.cluster.local
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        name: marble-injector
        namespace: marblerun
        path: "/mutate-no-sgx"
    rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: "Namespaced"
    namespaceSelector:
      matchLabels:
        marblerun/monitor: marblerun
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None